### ISSUE TITLE
Invalid check for classification size

### ISSUE THREAD

**Issue by qjuppet** [qupath/qupath-extension-stardist#15]
Currently, if the number of classes expected by QuPath is higher than the classes provided by the model, QuPath will take the missing classes in the rays channels as the number of rays is computed from the number of expected classes. The warning for invalid classification size is then never triggered.
![image](https://user-images.githubusercontent.com/13199998/156792000-f8fd3b65-3a89-47b4-9c3a-dec33d5cfd09.png)

**Comment by qjuppet** [comment]
I agree that this information might not be available from the model and then need to be provided from the builder by the user (as it is done right now), but in that case, the current check just below does not make sense as it will never fail:
![image](https://user-images.githubusercontent.com/13199998/156813865-4e2f3974-2e7f-4004-bffd-04418c3d4637.png)

**Comment by petebankhead** [comment]
Sorry, it has been a long time since I wrote or used that code so I still don't understand what *exactly* is wrong, and at this point on a Friday evening I'm not at my sharpest....

The StarDist code has to deal with a lot of scenarios: 
* 3 outputs, 2 outputs or channels concatenated
* classifications required or classifications not required
* classifications specified in the builder or classifications not specified in the builder
* a different numbers of rays from the default (since it can be specified when training StarDist)

where pretty much any combination is possible.

For concatenated output, there's no way for QuPath to distinguish between rays and channels if the information isn't given to the builder. So in this case it certainly could do the wrong thing, but it doesn't have enough information to do the right thing - because it needs to handle the case where there aren't any classifications anyway.

Can you describe specifically what combination of events isn't handled properly by the current code? Or can you say what the code *should* be?

The current code is quite involved, and I don't know what problem I should be looking for.

**Comment by petebankhead** [comment]
Note that the code you quote in the first post isn't *always* called:
https://github.com/qupath/qupath-extension-stardist/blob/main/src/main/java/qupath/ext/stardist/StarDist2D.java#L1102

QuPath supports StarDist models that have 3 outputs. In that case, the dimensions of the outputs are used to estimate the numbers of classifications. And in that case, the warning *can be* logged... I think.

But I'm getting this from reading the code / remembering, I don't have any classification models right now to test with.

It may well be the case that the warning can't be logged if the model concatenates outputs and the user doesn't specified the classifications... but in that case, I'd say QuPath has tried it's best and it's the user's fault :)

At least I think that's how it's meant to work, and why I yet see any bug.

As far as I'm aware, the original StarDist notebooks concatenate channels in the output using CSBDeep because that's needed for compatibility with the Fiji plugin - but QuPath can handle output without this channel concatenation. You can save a regular TensorFlow saved model without the CSBDeep export functions and use that in QuPath instead. This is better because it avoids most channel guesswork, and avoid needing to handle upsampled probability maps.

**Comment by qjuppet** [comment]
Indeed I did not took into account the output size, I was not expecting StarDist model to have this kind of shape as I'm always exporting them using the default export with CSBDeep, the check make sense for this situation so no bug :).

I was working with a binary classification and did not understood why I got only one classes as result all the times (it was related to the classes with id 0 being deleted, see keepClassifiedBackground), also StarDist starts the classes ids from 1 when training instead of 0 so there was some misunderstandings on the results I obtained since I used the same id system. To try to understand the problem, I increased the number of expected classes and started having a lot of results in multiple classes that I was not classifying in the model without any warning. I totally understand this information is not available and you cannot do anything on your side so that's the user's (me) fault.

Sorry for bothering you, have a nice weekend!
