### ISSUE TITLE
Measurement keys changed by StarDist

### ISSUE THREAD

**Issue by asquire** [qupath/qupath-extension-stardist#27]
I notice that when I run StarDist (for 0.4.0) on Qupath 0.4.2 with the measurement options the displayed measurement keys for the segmented cells are different to the measurement keys displayed when running the standard cell detection. For example with StarDist the key is ordered '<Channel>:<Cell ROI>:<Measurement>' whereas the standard cell detection orders the measurement key '<Cell ROI>:<Channel> <measurement>.

**Comment by petebankhead** [comment]
Hi @asquire I don't entirely understand your last sentence. But the use of different names with StarDist cell detection is intentional: https://forum.image.sc/t/measurement-names-for-stardist-vs-watershed-cell-detection/57566/2

I'm not certain that it was a *good* idea to use different names, and I think perhaps the naming scheme for the StarDist detection might need to change in the future, but if that's what you're referring to then it at least isn't a bug.

The built-in *Cell detection* is one of the first commands added to QuPath, and it calculates all the measurements during detection. The StarDist extension decouple the measurement from detection. In the future, I'd like to add more cell detection alternatives to QuPath. If so, they should use the same naming as StarDist and not the original Cell detection (but perhaps the names should still be revised if the order of the different name parts isn't good).

**Comment by asquire** [comment]
Hi, thanks for the quick response and explanation.
Yes, I have a script for multi-labelled fluorescent tissue data where the user can decide to segment with StarDist or the standard Cell Detection. I perform a multi-measurement classification based on the measurement values, which I access using the measurement key values i.e. with pathObject.getMeasurements(). Since the measurement key description is changed depending on whether a StarDist or Cell Classification is run, I have to keep a track of these differences in my script…. so to access a pathCellObject measurement value after running StarDist I use, for example: cell.getMeasurements()[“CD3: Cell: Mean”], whereas to retrieve the same cell measurement value after running Cell Detection I have to use: cell.getMeasurements()[“Cell: CD3: mean”].  Even if these differences are intentional it still seems strange that I must use a different measurement key to retrieve the same measurement value depending on whether the measurement list was generated by StarDist or Cell Detection. 
Even if StarDist decouples the measurements, having a standard format for the key descriptions, independent of the detection methods, would still seem to make the most sense(?).

**Comment by petebankhead** [comment]
I agree that having a standard format makes sense, and QuPath will probably switch to that. But currently the measurements *aren't* the same - they are calculated using completely different code, and potentially also at different resolutions.

The *Cell detection* code can't easily be changed, because then any classifiers that depend upon it would cease to work... which would likely cause problems for other users.
